name: Enhanced KuCoin Data Pipeline

on:
  workflow_dispatch:
    inputs:
      pipeline_mode:
        description: 'Pipeline mode'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
          - 'download_only'
          - 'verify_only'

jobs:
  enhanced-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # More time for full pipeline
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run enhanced pipeline
      run: node enhanced_worker.js
      env:
        PIPELINE_MODE: ${{ github.event.inputs.pipeline_mode }}
    
    - name: Show pipeline results
      run: |
        echo "=== ENHANCED PIPELINE RESULTS ==="
        if [ -d "./output" ]; then
          echo "✅ Output directory created"
          
          # Show downloaded files
          echo "📥 Downloaded files:"
          find ./output -name "*.zip" | while read file; do
            echo "  $(basename "$file") ($(stat -c%s "$file") bytes)"
          done
          
          # Show checksum files
          echo "🔍 Checksum files:"
          find ./output -name "*.CHECKSUM" | while read file; do
            echo "  $(basename "$file")"
          done
          
          # Show extracted files
          echo "📦 Extracted directory:"
          if [ -d "./output/BTCUSDT/extracted" ]; then
            ls -la ./output/BTCUSDT/extracted/ || echo "  (empty or not created)"
          fi
          
          # Show parquet files
          echo "📊 Parquet files:"
          if [ -d "./output/BTCUSDT/parquet" ]; then
            ls -la ./output/BTCUSDT/parquet/ || echo "  (empty or not created)"
          fi
          
          # Show summary
          if [ -f "./output/BTCUSDT/enhanced_summary.json" ]; then
            echo "=== PIPELINE SUMMARY ==="
            cat ./output/BTCUSDT/enhanced_summary.json | head -20
          fi
        else
          echo "❌ No output directory found"
        fi
    
    - name: Upload pipeline results
      uses: actions/upload-artifact@v4
      with:
        name: enhanced-btcusdt-pipeline-results
        path: ./output/
        retention-days: 7
      if: always()
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: |
          ./*.log
          ./output/*/enhanced_summary.json
        retention-days: 3
      if: always()
